Repository VIB-PSB/MINI-AC, pull requests merged in 2023-10, with the labels that each got.

#14 Hotfix/update tpj citation
  README.md
  docs/configuration_pipeline.md
Labels: documentation, priority

#9 Automated e2e test
  .github/workflows/test.yml
  .gitignore
  bin/add_go_names.py
  bin/getGO_xlsx_gw.py
  bin/getGO_xlsx_lb.py
  bin/getMotifCentricOutput_gw.py
  bin/getMotifCentricOutput_lb.py
  bin/getTFCentricOutput_gw.py
  bin/getTFCentricOutput_lb.py
  bin/processStats_bps_gw.py
  bin/processStats_bps_lb.py
  bin/processStats_gw.py
  bin/processStats_lb.py
  bin/reduce_go.py
  mini_ac.nf
  nf-test.config
  tests/data/zma_v4_chr1/zma_v4_noncod_merged_chr1.bed
  tests/data/zma_v4_chr1/zma_v4_promoter_5kbup_1kbdown_sorted_chr1.bed
  tests/inputs/ath/acr_files/DAR_Ep_iACR.bed
  tests/inputs/ath/acr_files/DAR_Va_iACR.bed
  tests/inputs/ath/de_files/DAR_Ep_iACR_DEGs_table.txt
  tests/inputs/ath/de_files/DAR_Va_iACR_DEGs_table.txt
  tests/inputs/zma_v4/acr_files/bundle_sheath_marand_top10k_chr1.bed
  tests/inputs/zma_v4/acr_files/mesophyll_marand_top10k_chr1.bed
  tests/inputs/zma_v4/de_files/maize_leaf_celltypes_degs_table.txt
  tests/inputs/zma_v4/exp_genes_files/maize_leaf_expressed_genes.txt
  tests/mini_ac.nf.test
  tests/mini_ac.nf.test.snap
  tests/nextflow.config
  workflows/miniac_gw.nf
  workflows/miniac_lb.nf
Labels: priority

#15 Release 1.1 - e2e test
  .github/workflows/test.yml
  .gitignore
  bin/add_go_names.py
  bin/getGO_xlsx_gw.py
  bin/getGO_xlsx_lb.py
  bin/getMotifCentricOutput_gw.py
  bin/getMotifCentricOutput_lb.py
  bin/getTFCentricOutput_gw.py
  bin/getTFCentricOutput_lb.py
  bin/processStats_bps_gw.py
  bin/processStats_bps_lb.py
  bin/processStats_gw.py
  bin/processStats_lb.py
  bin/reduce_go.py
  example/outputs/GO_enrichment/mesophyll_marand_top10k_GO_enrichment.txt
  mini_ac.nf
  nf-test.config
  tests/data/zma_v4_chr1/zma_v4_noncod_merged_chr1.bed
  tests/data/zma_v4_chr1/zma_v4_promoter_5kbup_1kbdown_sorted_chr1.bed
  tests/inputs/ath/acr_files/DAR_Ep_iACR.bed
  tests/inputs/ath/acr_files/DAR_Va_iACR.bed
  tests/inputs/ath/de_files/DAR_Ep_iACR_DEGs_table.txt
  tests/inputs/ath/de_files/DAR_Va_iACR_DEGs_table.txt
  tests/inputs/zma_v4/acr_files/bundle_sheath_marand_top10k_chr1.bed
  tests/inputs/zma_v4/acr_files/mesophyll_marand_top10k_chr1.bed
  tests/inputs/zma_v4/de_files/maize_leaf_celltypes_degs_table.txt
  tests/inputs/zma_v4/exp_genes_files/maize_leaf_expressed_genes.txt
  tests/mini_ac.nf.test
  tests/mini_ac.nf.test.snap
  tests/nextflow.config
  workflows/miniac_gw.nf
  workflows/miniac_lb.nf
Labels: new release
